### ISSUE TITLE
error: Uncaught (in promise) Error: npm:iter-ops@3.0.7

### ISSUE THREAD

**Issue by denizdogan** [denoland/deno_doc#316]
I can't seem to figure this one out. For some reason, only when using deno_doc as a library, it errors out on `npm:` dependencies. Any ideas why?

```ts
// example-module.ts
import { flatMap } from "npm:iter-ops@3.0.7";
import { delay } from "https://deno.land/std@0.175.0/async/delay.ts";

/**
 * This is a very important function.
 */
export const flatMap_ = flatMap;

/**
 * Don't worry about this function.
 */
export const delay_ = delay;
```

```ts
// main.ts
import { doc } from "https://deno.land/x/deno_doc@0.53.0/mod.ts";

const moduleURL = new URL("./example-module.ts", import.meta.url).href;
console.log(moduleURL);

const output = await doc(moduleURL);
console.log(output);
```

```
$ deno run -A ./main.ts
file:///Users/deniz/Code/temp/example-module.ts
error: Uncaught (in promise) Error: npm:iter-ops@3.0.7
      const ret = new Error(getStringFromWasm0(arg0, arg1));
                  ^
    at __wbg_new_651776e932b7e9c7 (https://deno.land/x/deno_doc@0.53.0/lib/deno_doc.generated.js:332:19)
    at <anonymous> (https://deno.land/x/deno_doc@0.53.0/lib/deno_doc_bg.wasm:1:1962531)
    at <anonymous> (https://deno.land/x/deno_doc@0.53.0/lib/deno_doc_bg.wasm:1:454192)
    at <anonymous> (https://deno.land/x/deno_doc@0.53.0/lib/deno_doc_bg.wasm:1:1475842)
    at <anonymous> (https://deno.land/x/deno_doc@0.53.0/lib/deno_doc_bg.wasm:1:1468810)
    at <anonymous> (https://deno.land/x/deno_doc@0.53.0/lib/deno_doc_bg.wasm:1:1915267)
    at __wbg_adapter_16 (https://deno.land/x/deno_doc@0.53.0/lib/deno_doc.generated.js:205:6)
    at real (https://deno.land/x/deno_doc@0.53.0/lib/deno_doc.generated.js:189:14)

$ deno doc --json ./main.ts
[
  {
    "kind": "import",
    "name": "doc",
    "location": {
      "filename": "file:///Users/deniz/Code/temp/main.ts",
      "line": 1,
      "col": 0
    },
    "declarationKind": "private",
    "importDef": {
      "src": "https://deno.land/x/deno_doc@0.53.0/mod.ts",
      "imported": "doc"
    }
  }
]

$ deno --version
deno 1.30.0 (release, aarch64-apple-darwin)
v8 10.9.194.5
typescript 4.9.4
```

**Comment by dsherret** [comment]
deno_doc has no concept of npm dependencies at the moment. All that functionality is only in the CLI.

**Comment by crowlKats** [comment]
Closing this as this is as intended, and adding npm capability revolves around a resolver & loader based on `node_resolver`
