### ISSUE TITLE
RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by devingfx** [denoland/deno_doc#326]
Hi!
I have got a low level wasm error that I can't understand.

Steps to reproduce:

deno.jsonc
```javascript
{
	"imports": {
		"std/": "https://deno.land/std@0.177.0/"
	},
}
```

docs.js
```javascript
import { doc } from "https://deno.land/x/deno_doc@0.58.0/mod.ts"
import { resolve, toFileUrl } from 'std/path/mod.ts'


console.log( toFileUrl(resolve('./Object/foo.js')) )
console.log( await doc(toFileUrl(resolve('./Object/foo.js'))) )

```
Object/foo.js
```javascript

/**
 * Object/foo
 */
export default 42

```

Error:
```bash
dig@dig-terra:~/dev/some-project$ deno run -A docs.js 
URL {
  href: "file:///home/dig/dev/some-project/Object/foo.js",
  origin: "null",
  protocol: "file:",
  username: "",
  password: "",
  host: "",
  hostname: "",
  port: "",
  pathname: "/home/dig/dev/some-project/Object/foo.js",
  hash: "",
  search: ""
}
error: Uncaught (in promise) RuntimeError: memory access out of bounds
    at <anonymous> (https://deno.land/x/deno_doc@0.58.0/lib/deno_doc_bg.wasm:1:2007454)
    at <anonymous> (https://deno.land/x/deno_doc@0.58.0/lib/deno_doc_bg.wasm:1:1967225)
    at <anonymous> (https://deno.land/x/deno_doc@0.58.0/lib/deno_doc_bg.wasm:1:1955069)
    at passStringToWasm0 (https://deno.land/x/deno_doc@0.58.0/lib/deno_doc.generated.js:79:11)
    at Object.doc (https://deno.land/x/deno_doc@0.58.0/lib/deno_doc.generated.js:230:16)
    at doc (https://deno.land/x/deno_doc@0.58.0/mod.ts:81:15)
    at async file:///home/dig/dev/some-project/docs.js:6:14
```

Mainwhile `deno doc` is working perfectly!

```bash
dig@dig-terra:~/dev/some-project$ deno doc Object/foo.js 
Defined in file:///home/dig/dev/some-project/Object/foo.js:5:0

var default: 42
  Object/foo

```

**Comment by oscarotero** [comment]
I have the same error with this code:

```js
import { doc } from "https://deno.land/x/deno_doc@0.65.0/mod.ts";

const docs = await doc("https://deno.land/x/lume@v1.18.4/plugins/esbuild.ts", {
  includeAll: true,
});
```

It doesn't fail if the `includeAll` option is false.
