### ISSUE TITLE
issues with the js module

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno_doc#525]
```ts
import { doc } from "https://deno.land/x/deno_doc@0.117.0/mod.ts";
import { pathToFileURL } from "node:url"; // this line trigger the error

console.log(await doc(import.meta.url));
```

error
```
error: Uncaught (in promise) Error: Failed resolving 'node:url' from 'file:///home/mrcool/dev/deno/lab/a.ts'.
      const ret = new Error(getStringFromWasm0(arg0, arg1));
                  ^
    at __wbg_new_a64e3f2afc2cf2f8 (https://deno.land/x/deno_doc@0.117.0/deno_doc_wasm.generated.js:404:19)
    at <anonymous> (file:///home/mrcool/.local/share/deno-wasmbuild/e7a23ed6bef70972bd288456786eaea32d8aa736d7ad6e9e71df1e02640116c1.wasm:1:89851)
    at <anonymous> (file:///home/mrcool/.local/share/deno-wasmbuild/e7a23ed6bef70972bd288456786eaea32d8aa736d7ad6e9e71df1e02640116c1.wasm:1:2384079)
    at <anonymous> (file:///home/mrcool/.local/share/deno-wasmbuild/e7a23ed6bef70972bd288456786eaea32d8aa736d7ad6e9e71df1e02640116c1.wasm:1:2826498)
    at __wbg_adapter_48 (https://deno.land/x/deno_doc@0.117.0/deno_doc_wasm.generated.js:240:8)
    at real (https://deno.land/x/deno_doc@0.117.0/deno_doc_wasm.generated.js:225:14)
    at ext:core/01_core.js:303:9
    at eventLoopTick (ext:core/01_core.js:169:7)
```

note that deno doc works correctly

Another note `doc` takes specifier argument as string but I think it should be URL since that's what it accepts at runtime

**Comment by sigmaSd** [comment]
Also its slow, any way to improve the performance in the future ? it takes atleast one second to run
```ts
import { doc } from "https://deno.land/x/deno_doc@0.117.0/mod.ts";

console.log(performance.now().toFixed(2), "ms");
await doc(import.meta.url);
console.log(performance.now().toFixed(2), "ms");
```
```
66.81 ms
1141.09 ms
```
