### ISSUE TITLE
0.162 throws `Error: relative URL without a base`, but 0.161 works fine ?

### ISSUE THREAD

**Issue by lowlighter** [denoland/deno_doc#680]
For some reason on 0.162 the deno/doc doesn't work on my module, but the 0.161 works fine, not sure whether there was something changed in url resolution

About the project:
- uses deno workspaces
- has imports map (in deno.jsonc)

Minimal repro
```ts
import { doc as doc1 } from "jsr:@deno/doc@0.161"
import { doc as doc2 } from "jsr:@deno/doc@0.162"

console.log("0.161", await doc1("jsr:@mizu/render/server").then(() => "OK").catch((error) => error))
console.log("0.162", await doc2("jsr:@mizu/render/server").then(() => "OK").catch((error) => error))
```

Example output
```
PS C:\Users\local\Documents\GitHub\mizu> deno --version
deno 2.1.4 (stable, release, x86_64-pc-windows-msvc)
v8 13.0.245.12-rusty
typescript 5.6.2
PS C:\Users\local\Documents\GitHub\mizu> deno run -A .\test.ts
0.161 OK
0.162 Error: relative URL without a base
    at __wbg_new_28c511d9baebfa89 (https://jsr.io/@deno/doc/0.162.1/deno_doc_wasm.generated.js:651:19)
    at <anonymous> (wasm://wasm/011a3ff2:1:136374)
    at <anonymous> (wasm://wasm/011a3ff2:1:3139281)
    at <anonymous> (wasm://wasm/011a3ff2:1:3723228)
    at __wbg_adapter_51 (https://jsr.io/@deno/doc/0.162.1/deno_doc_wasm.generated.js:290:6)
    at real (https://jsr.io/@deno/doc/0.162.1/deno_doc_wasm.generated.js:274:14)
    at ext:core/01_core.js:291:9
    at eventLoopTick (ext:core/01_core.js:175:7)

**Comment by CyanChanges** [comment]
There's a breaking change

```diff
import { doc as doc1 } from "jsr:@deno/doc@0.161"
import { doc as doc2 } from "jsr:@deno/doc@0.162"

console.log("0.161", await doc1("jsr:@mizu/render/server").then(() => "OK").catch((error) => error))
-console.log("0.162", await doc2("jsr:@mizu/render/server").then(() => "OK").catch((error) => error))
+console.log("0.162", await doc2(["jsr:@mizu/render/server"]).then(() => "OK").catch((error) => error))

**Comment by crowlKats** [comment]
Closing as nothing is actually broken, just the API changed.
